### ISSUE TITLE
root 의 rest-api-*.html 들을 다른 디렉토리로 정리

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cloud-barista.github.io#5]
현재 repo root 에 rest-api-*.html 들이 있는데,
현재도 개수가 많고, 앞으로 점점 더 많아질 것입니다.
이들을 다른 디렉토리 안에 넣으면 좋을 것 같습니다.

**Comment by innodreamer** [comment]
현재 root 디렉토리의 rd-*.html 파일은 다른 URL로의 redirection 기능을 하는 파일인데, 그 파일들을 다른 디렉토리를 생성해서 정리하면 그 파일에 대한 redirection 기능이 실행되지 않습니다. 
혹시 다른 방법이 있는지 더 생각해보겠습니다.
